name: Hello world samle workflow
on: push
#  workflow_dispatch:
#    input:
#      name:
#        description: "Switch-Over Date"
#        default: "DDMMYYYY"
#        required: true

jobs:
  hello-job:
    #runs-on: 
    #  labels: [self-hosted, Linux, X64, dev]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Echo text
        run: 'echo "Hello, world!"'
        
      - name: cat /etc/hosts
        run: cat /etc/hosts

      - name: add some entries to hosts file
        run: | 
          echo "10.x.2.x myhost" | sudo tee -a /etc/hosts

      - name: Check what has been added
        run: cat /etc/hosts

      - name: Install ansible on runner
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: "9.3.0"

      - name: Check version of the ansible
        run: |
          echo "Print the Ansible version"
          ansible-playbook --version
        
      - name: run the playbook
        run: ansible-playbook /hello-world-repo/playbook.yml -vvv
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.12.4/x64
          PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib/pkgconfig
          Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
          Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
          Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib

  List-Job:
    runs-on: 
      labels: [self-hosted, Linux, X64, dev]
    steps:
      - name: List
        run: ls

  CAT_JOB:
    runs-on: 
      labels: [self-hosted, Linux, X64, dev]
    steps:
      - name: cat sshkey file
        run: cat ~/.ssh/id_ed25519

      - name: cat sshkey pub file
        run: cat ~/.ssh/id_ed25519.pub
  ETC_JOB:
    runs-on:
      labels: [self-hosted, Linux, X64, dev]
    steps:
    - name: Take backup of etc/hosts
      run: ansible-playbook /home/lingaraj/automation/hello-world-repo/.github/workflows/playbook.yml
#      - name: Check file and replace line
#        ansible.builtin.linefile:
#          path: /etc/hosts
#          insertafter: '127.0.0.1 localhost'
#          line: '198.162.23.2 myvm'
