name: Hello world samle workflow
on: push
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: 'echo "Hello, world!"'

      - name: List
        run: ls

      - name: cat etc/hosts file
        run: cat /etc/hosts
        
      - name: Check file and replace line
        ansible.builtin.linefile:
          path: /etc/hosts
          insertafter: '127.0.0.1 localhost'
          line: '198.162.23.2 myvm'