name: Hello world samle workflow
on: push
#  workflow_dispatch:
#    input:
#      name:
#        description: "Switch-Over Date"
#        default: "DDMMYYYY"
#        required: true

jobs:
  hello-job:
    #runs-on: 
    #  labels: [self-hosted, Linux, X64, dev]
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: 'echo "Hello, world!"'
        
      - name: cat /etc/hosts
        run: cat /etc/hosts

      - name: add some entries to hosts file
        run: | 
          echo "10.x.2.x myhost" | sudo tee -a /etc/hosts

      - name: Check what has been added
        run: cat /etc/hosts

      - name: Install ansible on runner
        uses: alex-oleshkevich/setup-ansible@VERSION
        with:
          version: "9.3.0"

      - name: Check version of the ansible
        run: ansible-playbook --version
      #- name: run the playbook
      #  run: ansible-playbook playbook.yml 

  List-Job:
    runs-on: 
      labels: [self-hosted, Linux, X64, dev]
    steps:
      - name: List
        run: ls

  CAT_JOB:
    runs-on: 
      labels: [self-hosted, Linux, X64, dev]
    steps:
      - name: cat sshkey file
        run: cat ~/.ssh/id_ed25519

      - name: cat sshkey pub file
        run: cat ~/.ssh/id_ed25519.pub
  ETC_JOB:
    runs-on:
      labels: [self-hosted, Linux, X64, dev]
    steps:
    - name: Take backup of etc/hosts
      run: ansible-playbook playbook.yml
#      - name: Check file and replace line
#        ansible.builtin.linefile:
#          path: /etc/hosts
#          insertafter: '127.0.0.1 localhost'
#          line: '198.162.23.2 myvm'
