name: Hello world samle workflow
on:
  workflow_dispatch:
    input:
      name:
        description: "Switch-Over Date"
        default: "DDMMYYYY"
        required: true

jobs:
  hello-job:
    runs-on: 
      labels: [self-hosted, Linux, X64, dev]
#    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: 'echo "Hello, world!"'

  List-Job:
    runs-on: 
      labels: [self-hosted, Linux, X64, dev]
    steps:
      - name: List
        run: ls

  CAT_JOB:
    runs-on: 
      labels: [self-hosted, Linux, X64, dev]
    steps:
      - name: cat sshkey file
        run: cat ~/.ssh/id_ed25519

#      - name: Check file and replace line
#        ansible.builtin.linefile:
#          path: /etc/hosts
#          insertafter: '127.0.0.1 localhost'
#          line: '198.162.23.2 myvm'
