name: Deploy with Ansible

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
    input:
      name:
        description: "Switch-Over Date"
        default: "DDMMYYYY"
        required: true
#    workflow_dispatch:
#    input:
#      name:
#        description: "Switch-Over Date"
#        default: "DDMMYYYY"
#        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debugging - Print Current Directory
        run: pwd

      - name: Debugging - List Files
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook /home/lingaraj/automation/hello-world-repo/playbook.yml
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.12.4/x64
          PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib/pkgconfig
          Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
          Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
          Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib
