---
- hosts: localhost 
  become: true
  tasks:
  - name: Take backup of the etc/hosts
    copy:
      src: /etc/hosts
      dest: ~/hosts_bak.bak
      owner: root
      group: root
      backup: yes
  - name: cat /etc/hosts
    shell: |
    echo "cat hosts from etc"
    cat /etc/hosts
    echo "cat hosts from home"
    cat ~/hosts_bak.bak
  - name: Append line at end
    run |
    echo "10.20.30.40 lingaraj.ae" | sudo tee -a ~/.hosts_bak.bak
    echo "Check whether line appended or not"
    cat ~/.hosts_bak.bak
    
  - name: Change the Etc hosts entry
    linefile:
      path: ~/.hosts_bak.bak
      regexp: "10.20.30.40 lingaraj.ae"
      line: "10.20.30.60 lingaraj.ae"
      backrefs: yes
  - name: cat etc from home
    shell: |
    echo "cat hosts from home"
    cat ~/hosts_bak.bak
